### PR TITLE
Support omitting struct fields from [de]serialization.

### PR DESCRIPTION
**Pull request by veelo**
Hi, and thank you for sbin!

I hope you'll like this small contribution. It would greatly increase the usability for us. If you do, would you mind tagging a new release with this?

Best regards,
Bastiaan.

### CODE REVIEW

**Comment by deviator** [comment]
Hi @veelo! Thank you for request!
I think one moment in code need to be changed: name of UDA (case of first liters of name)
https://dlang.org/dstyle.html#naming_udas
UDA can be `enum sbinSkip;` or construct function
```
struct SBinSkip {}
auto sbinSkip() { return SBinSkip.init; }
```

**Comment by veelo** [comment]
I did not know that, you're right. I'll push an update shortly. I didn't know an enum could be used as well, that is probably the cleanest.

**Comment by veelo** [comment]
If you prefer I can try to squash the commits, but I think I'll have to resubmit the PR in that case because I forgot to create a branch for this.

**Comment by deviator** [comment]
@veelo I was tag new version `v0.6.0`, it's on dub right now.

**Comment by veelo** [comment]
O, that's quick. Thank you!

**Pull request merged**
